<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <RootNamespace>DigitalPulse.Worker</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DigitalPulse.Application\DigitalPulse.Application.csproj" />
    <ProjectReference Include="..\DigitalPulse.Infrastructure\DigitalPulse.Infrastructure.csproj" />
  </ItemGroup>
</Project>
